DX copy-edit
ThingLabsIo/ThingLabsIo.github.io pull request #94
Opened 2016-12-01 22:57 UTC by jonbgallant

The PR is large, but most of the changes are tweaks are just copy-edit to clear up language.

2016-12-18 00:13 UTC, rpedersen requested changes
minor issues with extra spaces
One spot where lab 97 needs to be lab 7

2016-12-18 00:13 UTC, rpedersen commented on pages/workshop/cs/01-getting-started.md
> +The labs in the Connected Nightlight Workshop build on each other to enable you to prototype your own Internet of Things (IoT) devices. You will use the Microsoft .NET Framework to build an applicati
There is an extra space between the "or" and "a" before DragonBoard 410c

2016-12-18 00:13 UTC, rpedersen commented on pages/workshop/cs/02-setup-rpi2.md
> +In this section you prepared your Raspberry Pi 2 for the subsequent labs. Next you will do the IoT equivalent  of a 'Hello, World!' program: you will make an LED blink.
There is an extra space before "of a" prior to 'Hello, World!'

2016-12-18 00:13 UTC, rpedersen commented on pages/workshop/thingy-4-windows/00-home.md
> +<a class="radius button small" href="{{ site.url }}/workshop/thingy-4-windows/storing-displaying-data/">Estimated time to complete: 30-minutes. Go to  'Lab 06: Storing & Displaying IoT Data' ›</a>
Extra space before 'Lab 06:

2016-12-18 00:13 UTC, rpedersen commented on pages/workshop/thingy-4-windows/00-home.md
> +<a class="radius button small" href="{{ site.url }}/workshop/thingy-4-windows/sending-c2d-messages/">Estimated time to complete: 20-minutes. Go to  'Lab 07: Sending Cloud to Device (C2D) Messages' ›<
Extra space before 'Lab 07:

2016-12-18 00:13 UTC, rpedersen commented on pages/workshop/thingy-4-windows/07-sending-c2d-messages.md
> +title: "Lab 97: Sending Cloud-to-Device (C2D) Messages"
hould be "Lab 7:"

2016-12-19 23:45 UTC, jonbgallant commented
Edits made.  Thanks for the review!

2016-12-20 20:06 UTC, merged